apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: job-info-collector-default-deny
  labels:
    app.kubernetes.io/name: job-info-collector
    app.kubernetes.io/part-of: job-info-collector
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: job-info-collector
  policyTypes:
    - Ingress
    - Egress
