fullnameOverride: kube-prometheus-stack

grafana:
  enabled: true
  adminUser: admin
  adminPassword: change-me
  persistence:
    enabled: true
    type: pvc
    accessModes:
      - ReadWriteOnce
    size: 2Gi
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      isDefault: false

prometheus:
  prometheusSpec:
    scrapeInterval: 60s
    evaluationInterval: 60s
    retention: 7d
    retentionSize: 15GB
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 15Gi
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
