apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/minio/operator.git
    targetRevision: v7.1.1
    path: helm/operator
    helm:
      releaseName: minio-operator
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
