apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: infrastructure
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cluster
      targetRevision: 0.6.1
      helm:
        releaseName: postgres
        valueFiles:
          - $values/k8s/infra/postgres/cluster.values.yaml
    - repoURL: https://github.com/kunxie/macmini-lab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
